server:
  port: 8080

spring:
  application:
    name: comic-service
  datasource:
    url: jdbc:mysql://example.com:3306/pomic
    username: root
    password: Ufoufo123456!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/comics

graphql:
  servlet:
    mapping: /graphql
  playground:
    enabled: true
